---
- hosts: awsEc2
  user: ubuntu
  sudo: yes
  tasks:
    - name: Apt tasks
      apt: update_cache=yes
      apt: upgrade=dist
    - name: Copy over neuralNets
      copy: src=neuralNet dest=/home/ubuntu/ owner=ubuntu group=ubuntu
    - name: Copy over public keys
      lineinfile: dest=/home/ubuntu/.ssh/authorized_keys line="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC8BCF79erYQjyiWlzSyJs+SCiGr6D9nkb6QVMTaQFykF4wt1OzSdZR6apN4lB8YVIt9DHDZ5DlFPWuLL6D+kkeBpRtCJNaYhS7BEsk8y23pE1ZfY+lt3AnfD7171X3Rn7o1PYGNo1ucB2LP3HXMfhz9poowGRIN4a6v9idGyduTI+zOWM33Lb+9Gt4ktX4BpBMzYNmD3qGsRbE0q8p/WzXt8frTxOM4XqikUFdIO2CnF262rQR9rYZ1b/9psZ6n2DHHf9LrP84P1ZeJ3VzRvZQ+hNryUQwyfkPR7qB5t1kWtoRXfDsXeUjDI+yX4Ge6od2RVsBL/RsOdPY2aUiolTaRdnmPd6mETrG83WV/bEcml84xRouXY8rEeF1Po+YctfGjskn5oLZCRxlc/KHyY2ZCjdY3p4GSwoSpiwDGLB5VtlNYkhsbkgAllOflhGdeon7+Y4LuqXwzpocvtrRs5m5h1VT/cBmOuRLNCDp2x8DpntLQUXgrQN50f4lClj9NrdbTT9rndmh47oPfnBL3xrn8n5dUw5VlTxvuXaTr+Rf24DW+/w7upklTz60Qo04FQPktvTc5o+vIM2kBBHKv7uGug02kPLVfIZRnZtfU/tD92GjmeEpTL1M30ZgGCx1n8vjmLXnt5t80bPDFJYG2xkscWSTWEcUdJRR7Qkup7m3Uw== mxu@ncsu.edu" 
    - name: Install neuralNet requirements.txt
      pip: requirements=/home/ubuntu/neuralNet/requirements.txt
